### ISSUE TITLE
ViPER4Android works only in compatible mode

### ISSUE THREAD

**Issue by AndroMans** [ShadySquirrel/ViPER4Android#15]
Thanks for your V4A module included in the latest stable Magisk version.

My phone is Moto G2 4G LTE 2014 version running stock ROM Marshmallow 6.0. 

I am using the latest stable Magisk version 14.0 and downloaded your latest V4A materialized version
(viper4android_v40_magisk_v14_materialized.zip) from github and flashed it today using TWRP. All went well except that under the normal mode, the processing status was showing as NO when I play any music in my Google Play music app. I even tried the disable SElinux option under the developer mode in settings but of no avail. However, when I change the FX compatible mode to compatible, V4A was working fine, both under the phone speaker and headset. BTW, this is the only V4A version that worked for me. I also tried the other two V4A magisk modules created by ahiron/zackptg5. But, they did not
work. In fact, even the drivers did not load for me. So, a big thanks to you as your module works for me.

Now, I request your support with the following:

1. To make it work under the normal mode also with the processing status YES.

2. How I can use V4A for all my audio apps. Right now, it only works in my default Google Play Music app. I also use MXPlayer. But V4A doesn't work in that. I need to make it work for YouTube as well.

I have disabled my stock equalizer Audio FX app and I have also installed the following magisk modules Init.d Linker and 
Universal deep_buffer Remover by Ahiron/Zackptg5. 
But I am not able to use V4A for other audio apps.

Please let me know what I should do to make it happen.

Thank you once again for your V4A magisk module.

**Comment by ShadySquirrel** [comment]
With V4A working only in compatible mode, that means that some other audio effect is active and clashing with V4A. 
I'm gonna need audio_effects.conf file from your ROM and logcat while running V4A in both normal and compatible mode. My guess configuration got borked because all of other modules, and something is weird there.

**Comment by AndroMans** [comment]
Thank you for your immediate reply. 

I just checked my Magisk set up and found that I also have the "Audio Modification Library" module installed and another sound mod AM3D Zirene Sound - both by Ahiron and Zackptg5. I also sometimes use the AM3D Zirene sound mod for watching movies as its sound effects are great. I thought the Universal Deep Buffer Remover module from Ahiron would take care of having more than one sound mod in magisk.  But it seems that is not working for me. And would that be causing my V4A not to work in normal mode?

BTW, will there be any noticeable difference in V4A's performance in normal mode compared to the
compatible mode I currently have. Because, the sound I get now is excellent and that will do for me. 
And only if the normal mode will provide me the REAL experience of V4A, I think I would be fine with this as I also need AM3D Zirene sound mod.

Are there any other alternate solutions for this? Like running SELinux in permissive when I have to use V4A in normal mode. Is it possible? Basically, I want to use more than one sound mod for different purposes.

Also, for my 2nd question, is there something that I can do to make all my audio/video apps use the custom sound mod I have enabled in Magisk when it comes to the equalizer effects?

**Comment by ShadySquirrel** [comment]
Well, idea behind this module is to keep it pure, no frills and dependency hell V4A experience - honestly, using anything else besides V4A is a fully fledged battery drain for me, and I like keeping my system as light and secure as possible.

Yes, having multiple mods will make V4A work only in compatibility mode - if you want it to work on normal mode, it should be only mod installed. I'm not sure if there is any other way (than using audio_effects.conf) to configure order of priority for audio effects - there should be a 'Music effects' option in sound (well, it was there in earlier android versions) when you have multiple effects installed.  So no, that's in no way connected to deep buffer or anything else, just a way V4A works. At least when using my installer.

So, in short, if you want to keep all those mods, you should remove my module and use one depending on AML. 

To use V4A from my module, you don't need permissive sepolicy, because module injects V4A specific rules during boot time, using [Magisk's policy injection](https://github.com/ShadySquirrel/ViPER4Android/blob/master-materialized/common/post-fs-data.sh) - that's why it doesn't require you to install driver everytime you start V4A app - all configuration done during installation time is completed by module (you can check [installation script](https://github.com/ShadySquirrel/ViPER4Android/blob/master-materialized/META-INF/com/google/android/update-binary#L133) if you're interested and have understanding how stuff works there), which means you get a driver depending on the platform, configured audio_effects and sepolicy workaround, you just have to run app and configure effects to your liking. I'm kind of sad other people would rather disable SELinux instead of properly patching sutff - you're getting proprietary libraries and you have no idea what else are they doing besides their main appliance.

About your second issue, I guess other mods have priority over V4A there. If you really want to keep this configuration you're using, try with Settings->Sound option I've mentioned above, or configuring effects per player (I know BlackPlayer supports using external equalizers). I have only V4A on my phone, and it's really omni present - works with BlackPlayer, VLC, Play Music; in games, in all apps using sound output (heck, even in Google Assistant :D)

**Comment by AndroMans** [comment]
Thanks for the detailed response and after some time, I will try your V4A alone in Magisk and see if it works in the normal mode as well. 

Talking of Magisk's policy injection that you have used, did I understand correctly that even for the current compatible mode running of your V4A, already my SELinux is running in Permissive mode only for that audio session OR boot session, without me doing anything explicitly to disable SElinux?

Also, I am just curious to know if your V4A working in normal mode would make any noticeable difference in how the audio output sounds compared to my current compatible mode, which is very good so far I have heard with my head phones. I guess you would have tested the sound output in both modes, so I would like to hear from you. :D)

Thanks again.

**Comment by ShadySquirrel** [comment]
I'm glad to help :) Just don't forget to remove ALL sound mods, reboot and then install mine. Just to avoid mess-up with audio effects configuration, because script pulls your runtime configuration if you install from Magisk manager.

About sepolicy stuff - your session is completely in Enforcing mode, and stays that way, no workarounds or mode changes when V4A is active. Since SELinux is basically a set of rules governing read/write/exec/access permissions for libraries and apps on your device, and magisk-policy tool is used to add rules necessary for V4A libs to load and work. No magical switches and hacks, just plain proper use of tools I have :D

I can tell you that it makes no difference between normal and compatible mode for me, probably because I use only V4A so no further processing is happening. My setup is great, but unchanged in previous 4-5 years (I have Panasonic headphones, model is HT161, I think, and Panasonic HJE125 earphones which are, for sub 10€ earphones, beasts by their own, so not much tinkering is needed). It would probably give additional boost with stuff like Dolby etc. but I never cared about that, to be honest with you. I like my sound as clean as possible and as similar to the original as possible.

**Comment by AndroMans** [comment]
Ok great. I plan to do it when I will upgrade my Magisk with the next stable release. At that time, I will follow your advice and contact you for any issues. And thanks for explaining how the Sepolicy change works in Magisk, and also about the normal and compatible mode sound output of your V4A.

Thank you for your support and please keep up your good work going. Expect more such Magisk modules in future. Cheers. :)

**Comment by ShadySquirrel** [comment]
You're welcome :) We'll see about modules, lol, I made this one because original module topjohnwu made stopped working with Magisk 12+, and I figured out, why not..

I'm closing this issue, please, open new one when need arises :)

Cheers.
