### ISSUE TITLE
"you need to install driver" issue

### ISSUE THREAD

**Issue by DEMONVoz** [ShadySquirrel/ViPER4Android#26]
1+3, OOS beta 30, oreo, magisk 15.3, clean installing with all wipe. viper working without magisk manager, after installing magisk manager viper not work, error "please install driver". i tried many versions of viper module, no one works
[logcat.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1667951/logcat.txt)
[magisk_log_20180126_160259.log](https://github.com/ShadySquirrel/ViPER4Android/files/1667956/magisk_log_20180126_160259.log)

**Comment by ShadySquirrel** [comment]
Add audio effect configuration files and I'll check it when I get home

**Comment by DEMONVoz** [comment]
[audio_effects.conf.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1669938/audio_effects.conf.txt)

**Comment by ShadySquirrel** [comment]
1. you're missing config file (there are two)
2. are you sure that module is installed? There is no V4A entry in that config.

**Comment by DEMONVoz** [comment]
[audio_effects.conf.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1669972/audio_effects.conf.txt)
[audio_policy_configuration.xml.txt](https://github.com/ShadySquirrel/ViPER4Android/files/1669973/audio_policy_configuration.xml.txt)
this is correct files

**Comment by ShadySquirrel** [comment]
Okay, I see that OOS has moved to xml configs. Since you haven't provided paths, I'm guessing that `audio_effects.conf` is from `/system/etc` and `audio_policy_configuration.xml` (which this module doesn't touch) is in `/system/vendor/etc` or `/vendor/etc`. My guess is that you're missing one, probably placed in `/system/vendor/etc/` with `xml` extension. So...

Can you try with [new version](https://github.com/ShadySquirrel/ViPER4Android/releases/tag/v6.0)? It's a prerelease in need of testing.

Save installation log, and provide all found configs (script will search for all config files existing and edit them, also you'll see in the log what's changed) and a logcat after restart.

**Comment by DEMONVoz** [comment]
the same problem



[logs.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1669993/logs.zip)

**Comment by DEMONVoz** [comment]
it very strange. so what i do:
1. all wipes in twrp
2. flashing OOS
3. reboot in recovery, flashing magisk without magisk manager, than flash your viper module
first boot in os viper working, but after installing magisk manager and rebooting viper already showing error

**Comment by DEMONVoz** [comment]
it very strange. so what i do:

all wipes in twrp
flashing OOS
reboot in recovery, flashing magisk without magisk manager, than flash your viper module
first boot in os viper working, but after installing magisk manager and rebooting viper already showing error

**Comment by ShadySquirrel** [comment]
First thing first, why are you installing Manager separately?

Second, can you list me the contents of `/sbin/.core/img/viper4android` and subfolders? I can see that Magisk is mounting just dummy directory and nothing else, so I'd like to see if all files are created during install.

Third thing: your device is using f2fs instead of ext4, and that's maybe causing problems with Magisk. Can you move your data partition to ext4?

**Comment by DEMONVoz** [comment]
[viper4android_material.zip](https://github.com/ShadySquirrel/ViPER4Android/files/1670024/viper4android_material.zip)

**Comment by DEMONVoz** [comment]
any thought why it happened and how to fix it?

**Comment by DEMONVoz** [comment]
i reinstall module again and it works for now, but after reboot the same error again. running randomly...

**Comment by ShadySquirrel** [comment]
I have no idea. Possible issues are:
* there are some issues with f2fs filesystem and Magisk (some flaw in f2fs implementation),
* Magisk bug where it wouldn't execute all scripts/mounts properly is present with your setup,
* Maybe some conflict with modules exist,
* Maybe you even had a bad download (I should probably start providing sha256 sums). 

I'd suggest to re-download my module, remove installed one completely, and reflash from Magisk manager and try again.

**Comment by DEMONVoz** [comment]
problem from my side, i know, but i don't now what i can do with this. i tried many times to re-install and re-download, but still random
thank you, i will try to found a solution

**Comment by ShadySquirrel** [comment]
You can try moving your partitions to ext4, if possible, or try using only my module, and seeing if that issue persists. Probably should fill an error report for @topjohnwu, too.
