### ISSUE TITLE
Stops processing when audio is paused and resumed again

### ISSUE THREAD

**Issue by ShiviSh** [ShadySquirrel/ViPER4Android#39]
Device Yureka PLus(YU5510)
Rom : crDroid (Oreo 8.1)
Magisk v16.0
List of Modules installed:
your V4A
Dolby atmos (by guitardedhero)
AML
Xposed

Viper is working perfectly without Dolby Atmos installed, as soon as i install dolby there is a wierd behaviour i observed ,i.e it works when i disable master power in viper exit from it and then re enable the master power it then works until the music is playing.
Viper also does not stat on bootup (when dolby is installed)

**Comment by ShiviSh** [comment]
magisk log
[magisk_log_20180417_201448.log](https://github.com/ShadySquirrel/ViPER4Android/files/1920345/magisk_log_20180417_201448.log)

**Comment by ShadySquirrel** [comment]
Well, you debugged it pretty well yourself because Dolby is clashing with V4A. I'm not sure that Dolby version supports AML so so may want to check if there is AML-supported Dolby, it should work with my module.

**Comment by ShadySquirrel** [comment]
Yes, but it seems that Dolby app has higher effect priority than V4A, and V4A is by design made to be only audio effect there, without any configuration, hacks etc.

Only solution I can recommend is that you try with Compatibility mode in V4A, it will let you use multiple audio effects. It won't have any affect on available configuration options, and will probably make it work without much pain.

**Comment by ShiviSh** [comment]
compatibility mode doesnt work

**Comment by ShadySquirrel** [comment]
Even after reboot?
