### ISSUE TITLE
Driver not installed after boot

### ISSUE THREAD

**Issue by michalbielejewski** [ShadySquirrel/ViPER4Android#43]
### Environment: 
- **Module and Magisk version:** 6.1.2 and 16.7 beta (also tried stable 16.0)
- **Phone model, OS and version:** OnePlus 3T, LineageOS 15.1 (`lineage-15.1-20180717-nightly-oneplus3-signed`) with Franco kernel, encrypted, 
- **SE Linux**: Tried both in enforcing and permissive.
- **List of installed modules:** [magisk-wifi-bonding](https://github.com/Magisk-Modules-Repo/magisk-wifi-bonding)
- **Is any other sound mod installed?** No, LOS AudioFX gets disabled during module install.

### Steps to reproduce the issue
1. Reboot
2. Run Viper4Android app
3. See that driver is not installed

### Additional info
- Reboot helps
- Occurs randomly
- Magisk is working fine, only V4A loses the driver
- Yes, I did wait for the Magisk notification to go away
 
Logs:
[boot.log](https://github.com/ShadySquirrel/ViPER4Android/files/2238990/boot.log) - during this boot the bug didn't occur, but maybe it still helps
[magisk_log_20180729_184911.log](https://github.com/ShadySquirrel/ViPER4Android/files/2238991/magisk_log_20180729_184911.log)
[conf.zip](https://github.com/ShadySquirrel/ViPER4Android/files/2238995/conf.zip) - audio_effects.conf and audio_effects.xml

**Comment by ShadySquirrel** [comment]
To answer all three: 

#43: there is a huge bug with encrypted devices and V4A, and I can't solve it because I have no idea if that's part of module, Magisk or V4A itself. Logs don't give anything useful, it just works partially/randomly or doesn't work at all. I had no luck on my device while it was encrypted, and I don't use my phone for audio anymore. It's basically a race condition between some components - if it manages to mount module files and inject sepolicy, it works, if it doesn't - well, it doesn't, and it happens so randomly it's unbelieveable.

#44 is probably an app error leading to driver crash - and since V4A as a project looks like it's been abandoned - no updates for a year now, and 8.1 support is basically a hack, I would suggest trying Materialised app/module. There were changes in way android's audio works and these should be followed by changes in app/library, but I have no control over that. 

#45 is probably connected to #44 (something is crashing driver), so materialised app may fix that one, too.

I'd really suggest to you to try using newer version of materialised V4A app (even one bundled in 'materialised' module version should be okay), it should have some better support - it fixed some quirks and issues I had on 7.1.

P.S: I'm probably going to drop this module soon, since I've got a dedicated media player with good sound quality and my phone probably won't receive any future updates, so it's getting impossible to test it against newer Android changes, which makes my interest in keeping this module maintained really low.

**Comment by michalbielejewski** [comment]
Thanks for you answer. 
It turns out that if I disable secure startup (not secure boot) it gets better.
It solves #43, #44 and #45.
What I've done is back everything up with TWRP (including storage - `/data/media`), did a full wipe (including `/system` and internal storage), restored TWRP backup and files from internal storage. 
During first boot it will encrypt `/data` and the phone won't unlock (just delete `/data/system/lockscreen.db` to fix that).
After that, the files are encrypted, but the encryption key is not, so it won't ask for a password/PIN/pattern during startup (and in recovery) and everything get successfully mounted.
Maybe there is a easier way to achieve this state - I don't know.

![screenshot_lineageos_settings_20180811-104410](https://user-images.githubusercontent.com/11682584/43989938-0f047be0-9d54-11e8-9179-32670e875202.png)
 

Maybe you should put a warning about this `README.md`?

**Comment by ShadySquirrel** [comment]
Sorry, I was on vacation so I couldn't answer faster.

I would avoid using this kind of setup, unprotected keys and all, to be honest, and not encourage it. Do you have this issue with other V4A modules?

I'm abandoning development on this one (it will work as long as magisk module template requirements aren't changed) so you may want to move to different module.
