### ISSUE TITLE
Works but strange behavior on bluetooth

### ISSUE THREAD

**Issue by cal525** [ShadySquirrel/ViPER4Android#6]
My phone us Huawei Mate 9, bootloader unlocked and rooted by Magisk 14, and it is connected to my bluetooth headphone all the times because I drive all day.

V4A works when I play music, watch youtube. However, it messes with my phone calls intermittently, sometimes phone calls were answers or rejected by the phone itself (without hitting any button on the bluetooth nor the phone) when the V4A Bluetooth Masterswitch is on.  

I think the oldest version with the Purple theme works without any problem. Where can I get the older versions of your V4A magisk module to test?

Thanks in advance.

Best regards,
Calvin

**Comment by ShadySquirrel** [comment]
New module version uses official V4A app, previous ones used Materialized app. Beware, official app isn't playing nice with Oreo. You can grab first two module versions from 'Releases' page, I'll soon add others there (got kind of lazy after module got published in Magisk repo)
P.S. Haven't tested this with bluetooth because my phone (Huawei Honor 5X) doesn't like any of 5 bluetooth handsfrees/speakers I have :D You're lucky your Huawei plays nice with those devices.

**Comment by cal525** [comment]
Where is the "Releases" page?

Can you please provide me the link?

Thanks.

**Comment by ShadySquirrel** [comment]
Under [Code -> Releases](https://github.com/ShadySquirrel/ViPER4Android/releases)
